export ENVIRONMENT="dev"
export STORAGE_PROJECT_ID="datamarket-np-cah"
export VIEW_PROJECT_ID="datamarket-np-cah"
export TERRAFORM_STATE_BUCKET="cah-dm-dev-provisioner"
export WRITER_SERVICE_ACCOUNT="sa-provisioner@datamarket-np-cah.iam.gserviceaccount.com"
