apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: tables.cft.dev
spec:
  group: cft.dev
  scope: Namespaced
  names:
    plural: tables
    singular: table
    kind: Table
  preserveUnknownFields: false
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            # TableSpec
            type: object
            properties:
              name:
                type: string
              fields:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                      nullable: true
                    type:
                      type: string
                      nullable: true
                    regulatory:
                      type: string
                      default: "none"
                      enum:
                        - none
                        - hipaa
                        - gdpr
                        - gxp
                        - sox
                        - pci
                        - pii
                        - dea
                    anonymizer:
                      type: string
                      nullable: true
                      description: function to anonymize the data [HIDE|HASH|SUBSTR(start,len)]
                      pattern: '(HIDE|HASH|SUBSTR\((\d+),( )?(\d+)+\))'
                    dateset_suffixes:
                      type: array
                      items:
                        type: string
                  required:
                    - name
            required:
             - fields
             - name
            # /TableSpec
